"""Server infrastructure modules."""

from ultrasync_mcp.server.config import (
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_TOOL_CATEGORIES,
    ENV_CLIENT_ROOT,
    ENV_WATCH_TRANSCRIPTS,
    MEMORY_HIGH_RELEVANCE_THRESHOLD,
    MEMORY_MEDIUM_RELEVANCE_THRESHOLD,
    TOOL_CATEGORIES,
    get_enabled_categories,
    get_enabled_tools,
)
from ultrasync_mcp.server.models import (
    AnchorMatchInfo,
    ConventionInfo,
    ConventionSearchResultItem,
    ConventionViolationInfo,
    FileInfo,
    MemorySearchResultItem,
    MemoryWriteResult,
    PatternMatch,
    PatternSetInfo,
    SearchResult,
    SessionThreadContext,
    SessionThreadInfo,
    StructuredMemoryResult,
    SymbolInfo,
    ThreadFileInfo,
    ThreadInfo,
    ThreadQueryInfo,
    ThreadToolInfo,
    WatcherStatsInfo,
)
from ultrasync_mcp.server.state import ServerState
from ultrasync_mcp.server.utils import (
    check_parent_process_tree,
    detect_coding_agent,
    format_search_results_tsv,
    get_transcript_parser,
    hex_to_key,
    key_to_hex,
)

__all__ = [
    # Config
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_TOOL_CATEGORIES",
    "ENV_CLIENT_ROOT",
    "ENV_WATCH_TRANSCRIPTS",
    "MEMORY_HIGH_RELEVANCE_THRESHOLD",
    "MEMORY_MEDIUM_RELEVANCE_THRESHOLD",
    "TOOL_CATEGORIES",
    "get_enabled_categories",
    "get_enabled_tools",
    # Models
    "AnchorMatchInfo",
    "ConventionInfo",
    "ConventionSearchResultItem",
    "ConventionViolationInfo",
    "FileInfo",
    "MemorySearchResultItem",
    "MemoryWriteResult",
    "PatternMatch",
    "PatternSetInfo",
    "SearchResult",
    "SessionThreadContext",
    "SessionThreadInfo",
    "StructuredMemoryResult",
    "SymbolInfo",
    "ThreadFileInfo",
    "ThreadInfo",
    "ThreadQueryInfo",
    "ThreadToolInfo",
    "WatcherStatsInfo",
    # State
    "ServerState",
    # Utils
    "check_parent_process_tree",
    "detect_coding_agent",
    "format_search_results_tsv",
    "get_transcript_parser",
    "hex_to_key",
    "key_to_hex",
]
