changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
      - github-actions[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Performance
      labels:
        - performance
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
